cmake_policy(SET CMP0091 OLD)

cmake_minimum_required(VERSION 3.22)
# ===== Build variant selection =====
#   OpenPixelOSD      -> base OSD (no VTX drivers)
#   OpenPixelOSD_VTX  -> OSD + VTX (RTC6705 / PA / MSP VTX)
set(BUILD_VARIANT "" CACHE STRING "Build variant: VTX")

set(TARGET_MCU "" CACHE STRING "Target MCU (e.g., STM32G431, STM32G474)")
# set default to G431 if not specified
if(NOT TARGET_MCU)
    set(TARGET_MCU STM32G431)
endif()

message(STATUS "Selected TARGET_MCU=${TARGET_MCU} BUILD_VARIANT=${BUILD_VARIANT}")

if(UNIX AND NOT APPLE)
    # Linux
    set(OS_SUPPORTED TRUE)
elseif(APPLE)
    # macOS
    set(OS_SUPPORTED TRUE)
else()
    set(OS_SUPPORTED FALSE)
endif()

if(OS_SUPPORTED)
    execute_process(
            COMMAND git rev-parse --abbrev-ref HEAD
            COMMAND cut -c1-10
            OUTPUT_VARIABLE GIT_BRANCH
            RESULT_VARIABLE BRANCH_RESULT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
    )
    if(BRANCH_RESULT EQUAL 0)
        message(STATUS "Git branch: ${GIT_BRANCH}")
        add_definitions(-DGIT_BRANCH=\"${GIT_BRANCH}\")
    else()
        message(STATUS "Git branch not found")
        add_definitions(-DGIT_BRANCH=\"\")
    endif()

    execute_process(
            COMMAND git rev-parse --short=8 HEAD
            OUTPUT_VARIABLE GIT_HASH
            RESULT_VARIABLE HASH_RESULT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
    )
    if(HASH_RESULT EQUAL 0)
        message(STATUS "Git hash: ${GIT_HASH}")
        add_definitions(-DGIT_HASH=\"${GIT_HASH}\")
    else()
        message(STATUS "Git hash not found")
        add_definitions(-DGIT_HASH=\"-.-.-\")
    endif()

    execute_process(
            COMMAND git describe --tags --abbrev=0
            OUTPUT_VARIABLE GIT_TAG
            RESULT_VARIABLE TAG_RESULT
            OUTPUT_STRIP_TRAILING_WHITESPACE
            ERROR_QUIET
    )
    if(TAG_RESULT EQUAL 0)
        message(STATUS "Git tag: ${GIT_TAG}")
        add_definitions(-DGIT_TAG=\"${GIT_TAG}\")
    else()
        message(STATUS "Git tag not found")
        add_definitions(-DGIT_TAG=\"unknown\")
    endif()
endif()

# Setup compiler settings
set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)

if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Debug")
endif()

# Set the project name
set(CMAKE_PROJECT_NAME OpenPixelOSD LANGUAGES C ASM)

# Include toolchain file
include("cmake/gcc-arm-none-eabi.cmake")

# Enable compile command to ease indexing with e.g. clangd
set(CMAKE_EXPORT_COMPILE_COMMANDS TRUE)

project(${CMAKE_PROJECT_NAME})
message(STATUS "Build type: " ${CMAKE_BUILD_TYPE})

add_executable(${CMAKE_PROJECT_NAME})


if(TARGET_MCU STREQUAL "STM32G431")
    message(STATUS "Building for STM32G431")
    add_compile_definitions(
            MCU_TYPE=\"STM32G431\"
            STM32G431xx
            LOW_RAM
    )
    set(LINKER_SCRIPT ${CMAKE_SOURCE_DIR}/stm32g431cbux_flash.ld)
    set(STARTUP_ASSEMBLY_FILE ./src/stm32g4xx/startup_stm32g431xx.s)
elseif(TARGET_MCU STREQUAL "STM32G474")
    message(STATUS "Building for STM32G474")
    add_compile_definitions(
            MCU_TYPE=\"STM32G474\"
            STM32G474xx
            HIGH_RAM
    )
    set(LINKER_SCRIPT ${CMAKE_SOURCE_DIR}/stm32g474ceux_flash.ld)
    set(STARTUP_ASSEMBLY_FILE ./src/stm32g4xx/startup_stm32g474xx.s)
    set(SOURCE src/fonts/font_system.c)
else()
    message(FATAL_ERROR "Unsupported MCU type: ${TARGET_MCU}")
endif()

if(BUILD_VARIANT STREQUAL "VTX")
    message(STATUS "Building generic target with VTX support")
    set(BUILD_NAME "_VTX")
    add_compile_definitions(BUILD_VARIANT_VTX)
    add_compile_definitions(TARGET_GENERIC)
    set(VARIANT_SRC
            ./src/rtc6705.c
            ./src/rf_pa.c
            ./src/vtx_msp.c
            ./src/settingsMenu.c
            ./src/targets/generic.c)
elseif(BUILD_VARIANT STREQUAL "PIXELVTX")
    message(STATUS "Building pixelVTX")
    set(BUILD_NAME "_pixelVTX")
    add_compile_definitions(BUILD_VARIANT_VTX)
    add_compile_definitions(TARGET_PIXELVTX)
    set(VARIANT_SRC
            ./src/rtc6705.c
            ./src/rf_pa.c
            ./src/vtx_msp.c
            ./src/settingsMenu.c
            ./src/targets/pixelVTX.c)
elseif(BUILD_VARIANT STREQUAL "PIXELVTX_COLOR")
    message(STATUS "Building pixelVTXcolor")
    set(BUILD_NAME "_pixelVTXcolor")
    add_compile_definitions(BUILD_VARIANT_VTX)
    add_compile_definitions(TARGET_PIXELVTX_COLOR)
    set(VARIANT_SRC
            ./src/rtc6705.c
            ./src/rf_pa.c
            ./src/vtx_msp.c
            ./src/settingsMenu.c
            ./src/targets/pixelVTX.c)
else()
  message(STATUS "Building generic target")
  set(VARIANT_SRC
            ./src/targets/generic.c)
endif()

add_compile_definitions(
        USE_FULL_LL_DRIVER
        USE_HAL_DRIVER
)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -T${LINKER_SCRIPT}")

add_subdirectory(cmake/stm32)

# Link directories setup
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE
)

# Add sources to executable
target_sources(${CMAKE_PROJECT_NAME} PRIVATE
        ${STARTUP_ASSEMBLY_FILE}
        ${SOURCE}
        ${VARIANT_SRC}
        ./src/stm32g4xx/stm32g4xx_it.c
        ./src/stm32g4xx/system_stm32g4xx.c
        ./src/stm32g4xx/sysmem.c
        ./src/stm32g4xx/syscalls.c
        ./src/stm32g4xx/system.c
        ./src/msp/msp.c
        ./src/gpio.c
        ./src/dac.c
        ./src/adc.c
        ./src/dma.c
        ./src/opamp.c
        ./src/tim.c
        ./src/comp.c
        ./src/uart.c
        ./src/usb.c
        ./src/flash.c
        ./src/video_gen.c
        ./src/video_overlay.c
        ./src/canvas_char.c
        ./src/msp_displayport.c
        ./src/msp_fc.c
        ./src/fonts/update_font.c
        ./src/video_graphics.c
        ./src/main.c
        ./src/settings.c

)

# Add include paths
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
        ./src/targets
        ./src/stm32g4xx
        ./src/msp
        ./src
)

# Add project symbols (macros)
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE

)

# Add linked libraries
target_link_libraries(${CMAKE_PROJECT_NAME}
        stm32cubemx

)


# Generate hex and bin files
set(HEX_FILE ${CMAKE_PROJECT_NAME}_${TARGET_MCU}${BUILD_NAME}.hex)
set(BIN_FILE ${CMAKE_PROJECT_NAME}_${TARGET_MCU}${BUILD_NAME}.bin)

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND ${CMAKE_OBJCOPY} -Oihex $<TARGET_FILE:${PROJECT_NAME}> ${PROJECT_BINARY_DIR}/${HEX_FILE}
        COMMAND ${CMAKE_OBJCOPY} -Obinary $<TARGET_FILE:${PROJECT_NAME}> ${PROJECT_BINARY_DIR}/${BIN_FILE}
        COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${PROJECT_NAME}>)

# make a zip file containing the hex, bin, map and elf
set(ZIP_NAME "${CMAKE_PROJECT_NAME}_${TARGET_MCU}_${CMAKE_BUILD_TYPE}${BUILD_NAME}")
set(TARGET_LANGUAGES "C;ASM")
set(MAP_FILE "${PROJECT_BINARY_DIR}/${CMAKE_PROJECT_NAME};LANGUAGES;${TARGET_LANGUAGES}.map")

# Create ZIP after build completes
add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E echo "Creating ${ZIP_NAME}.zip"
        COMMAND ${CMAKE_COMMAND} -E tar "cf" "${ZIP_NAME}.zip" --format=zip
        "${HEX_FILE}"
        "${BIN_FILE}"
        "${MAP_FILE}"
        "$<TARGET_FILE:${PROJECT_NAME}>"
        WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
        COMMENT "Creating ZIP archive: ${ZIP_NAME}.zip"
)

# Flash the device using dfu-util
add_custom_target(flash
        COMMAND dfu-util -a 0 -s 0x08000000:leave -D ${PROJECT_BINARY_DIR}/${BIN_FILE} -R )
